version: '3.3'
services:
    server: 
        build: 
            context: ./server
            dockerfile: ./.docker/dev.dockerfile
        network_mode: bridge
        ports:
            - "3000:3000"
        volumes: 
            - ./server:/usr/src/app
        links:
            - "database:database"
        depends_on:
            - database
