version: '3.3'
services:
    database: 
        build: 
            context: ./database
            dockerfile: ./Dockerfile
        network_mode: "bridge"
        volumes: 
            - ./database/data:/data
        ports:
            - "7474:7474"
            - "7687:7687"
